# Makefile.psp -- X millennium (xmil) PSP 移植ビルド
#
# 使い方:
#   make -f Makefile.psp objs   # エミュレーションコアのみコンパイル
#   make -f Makefile.psp        # EBOOT.PBP まで (フロントエンド統合後)
#
# 構成は px68k の Makefile.psp (PSPSDK build.mak 利用) に合わせている。

# ---------------------------------------------------------------- コア objs

ROOTOBJS = \
	xmil/pccore.o xmil/calendar.o xmil/debugsub.o xmil/ievent.o xmil/keystat.o xmil/nevent.o \
	xmil/statsave.o xmil/timing.o

CODECNVOBJS = \
	xmil/codecnv/eucsjis.o xmil/codecnv/eucucs2.o xmil/codecnv/sjiseuc.o \
	xmil/codecnv/sjisucs2.o xmil/codecnv/tcswap16.o xmil/codecnv/tcswap32.o \
	xmil/codecnv/textcnv.o xmil/codecnv/ucs2sjis.o xmil/codecnv/ucs2utf8.o \
	xmil/codecnv/utf8ucs2.o

COMMONOBJS = \
	xmil/common/_memory.o xmil/common/bmpdata.o xmil/common/lstarray.o xmil/common/milstr.o \
	xmil/common/parts.o xmil/common/profile.o xmil/common/rect.o xmil/common/resize.o \
	xmil/common/strres.o xmil/common/textfile.o xmil/common/wavefile.o

EMBEDOBJS = \
	xmil/embed/vramhdl.o xmil/embed/vrammix.o \
	xmil/embed/menu/dlgabout.o xmil/embed/menu/dlgcfg.o xmil/embed/menu/filesel.o \
	xmil/embed/menu/menustr.o \
	xmil/embed/menubase/menubase.o xmil/embed/menubase/menudlg.o \
	xmil/embed/menubase/menuicon.o xmil/embed/menubase/menumbox.o \
	xmil/embed/menubase/menures.o xmil/embed/menubase/menusys.o \
	xmil/embed/menubase/menuvram.o

FDDOBJS = \
	xmil/fdd/diskdrv.o xmil/fdd/fdd_2d.o xmil/fdd/fdd_d88.o xmil/fdd/fdd_ini.o \
	xmil/fdd/fdd_mtr.o xmil/fdd/fddfile.o xmil/fdd/newdisk.o

FONTOBJS = \
	xmil/font/font.o xmil/font/fontdata.o xmil/font/fontmake.o xmil/font/fontx1.o

IOOBJS = \
	xmil/io/cgrom.o xmil/io/cmt.o xmil/io/crtc.o xmil/io/ctc.o xmil/io/dipsw.o xmil/io/dmac.o \
	xmil/io/fdc.o xmil/io/iocore.o xmil/io/memio.o xmil/io/pcg.o xmil/io/ppi.o xmil/io/sio.o \
	xmil/io/sndboard.o xmil/io/subcpu.o xmil/io/vramio.o

SOUNDOBJS = \
	xmil/sound/opm.o xmil/sound/opmgenc.o xmil/sound/opmgeng.o xmil/sound/psg.o \
	xmil/sound/psggenc.o xmil/sound/psggeng.o xmil/sound/sndcsec.o xmil/sound/sndctrl.o \
	xmil/sound/sound.o xmil/sound/x1f.o

# Z80 コアは C 版 (z80c)。z80x/z80a* は x86 asm のため PSP では使えない。
Z80OBJS = \
	xmil/z80c/z80c.o xmil/z80c/z80c_cb.o xmil/z80c/z80c_ix.o xmil/z80c/z80c_iy.o \
	xmil/z80c/z80c_mn.o xmil/z80c/z80c_sb.o xmil/z80c/z80dmap.o xmil/z80c/z80mem.o

# vram は libretro/Makefile.common と同じ個別列挙 (x86 asm 版のある
# ファイルを除いた C 実装のみ)。
VRAMOBJS = \
	xmil/vram/make15.o xmil/vram/make24.o xmil/vram/makeatr.o xmil/vram/makechr.o \
	xmil/vram/makemix.o xmil/vram/makescrn.o xmil/vram/makesub.o xmil/vram/maketxth.o \
	xmil/vram/maketxtl.o xmil/vram/palettes.o xmil/vram/sdraw.o xmil/vram/sdrawq16.o \
	xmil/vram/scrndraw.o xmil/vram/vram.o

COREOBJS = \
	$(ROOTOBJS) $(CODECNVOBJS) $(COMMONOBJS) $(EMBEDOBJS) $(FDDOBJS) \
	$(FONTOBJS) $(IOOBJS) $(SOUNDOBJS) $(Z80OBJS) $(VRAMOBJS)

# ------------------------------------------------------- フロントエンド objs
FRONTEND_OBJS = \
	psp/xmil.o psp/scrnmng.o psp/soundmng.o psp/sysmng.o psp/sysmenu.o \
	psp/taskmng.o psp/timemng.o psp/trace.o psp/dosio.o psp/fontmng.o \
	psp/ini.o psp/joymng.o psp/mousemng.o psp/selfexec.o psp/perf.o psp/gu.o psp/softkbd.o psp/pspmenu.o

OBJS = $(COREOBJS) $(FRONTEND_OBJS)

TARGET = xmil

# PRX 形式 (px68k と同様。実行時ロードされるモジュールのリンクのため)
BUILD_PRX = 1

PSPDEV = $(shell psp-config -d)
PSPBIN = $(PSPDEV)/psp/bin
SDL_CONFIG = $(PSPBIN)/sdl2-config

# 最近の pspdev の sdl-config は prefix が壊れている (/psp) ので修正する
# (px68k から流用。フロントエンドが SDL を使う場合に効く。コアには不要)
SDL_INCLUDE =	$(shell $(SDL_CONFIG) --cflags | sed "s|-I/psp/|-I$(PSPDEV)/psp/|g")
SDL_LIB =	$(shell $(SDL_CONFIG) --libs | sed "s|-L/psp/|-L$(PSPDEV)/psp/|g")

# psp/ を先頭に置き compiler.h は必ず psp/compiler.h が使われるようにする。
# libretro/ は末尾: コアが参照するポート層ヘッダ (dosio.h scrnmng.h
# soundmng.h sysmng.h fontmng.h taskmng.h timemng.h trace.h xmil.h など) を
# 当面 libretro 版から借りる。統合時にフロントエンドが psp/ に同名ヘッダを
# 置けばそちらが優先される。
INCDIR = psp xmil xmil/codecnv xmil/common xmil/embed xmil/embed/menu \
	xmil/embed/menubase xmil/fdd xmil/font xmil/io xmil/sound xmil/vram \
	xmil/z80c xmil/libretro

# -G0: libretro の PSP ターゲットに合わせる。px68k では -G8 (小データを
# gp 相対で参照、約 -14%/frame) を使っているが、割り込みハンドラと $gp の
# 関係を監査してからでないと危険なので、まずは -G0 で始める。
# PGO: make PGO=gen で計測ビルド (PPSSPP で autotest を走らせると gcda が
# ~/.config/ppsspp/<このディレクトリの絶対パス>/ に落ちる)。回収して
# make PGO=use で最適化ビルド。どちらも make clean してから。
ifeq ($(PGO),gen)
PGOFLAGS = -DPXMIL_GCOV -fprofile-generate=ms0:/PSP/GAME/PXMIL/pgo \
	-fprofile-prefix-path=$(PWD) -fprofile-update=single
else ifeq ($(PGO),use)
PGOFLAGS = -fprofile-use=pgo -fprofile-prefix-path=$(PWD) \
	-fprofile-correction -Wno-missing-profile
endif

# バージョン文字列 (メニューに表示)
PXMIL_VER := $(shell date +%Y%m%d)-$(shell git rev-parse --short HEAD 2>/dev/null || echo dev)

CFLAGS = -G8 -O2 -Wall $(PGOFLAGS) $(SDL_INCLUDE) -DPXMIL_VER='"$(PXMIL_VER)"'

CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti
ASFLAGS = $(CFLAGS)

LIBDIR =
LDFLAGS =
# sdl2-config --libs が -lSDL2main -lSDL2 と PSP 側依存 (GU/GE/audio 等) を
# 返す。残りは newlib/libm。
LIBS = $(SDL_LIB) -lm -lpsppower -lpspsystemctrl_user

EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = X millennium for PSP
PSP_EBOOT_ICON = assets/icon0.png

PSPSDK = $(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build.mak

# コアのみコンパイル (リンクしない)。フロントエンド開発と並行用。
objs: $(COREOBJS)

.PHONY: objs

# バージョンが変わったらメニューを作り直す (build.mak の include 後に
# 置くこと: 先頭に置くとデフォルトターゲットになってしまう)
psp/pspmenu.o: $(wildcard .git/HEAD .git/index)
