# Makefile.psp -- X millennium (xmil) PSP 移植ビルド
#
# 使い方:
#   make -f Makefile.psp objs   # エミュレーションコアのみコンパイル
#   make -f Makefile.psp        # EBOOT.PBP まで (フロントエンド統合後)
#
# 構成は px68k の Makefile.psp (PSPSDK build.mak 利用) に合わせている。

# ---------------------------------------------------------------- コア objs

ROOTOBJS = \
	pccore.o calendar.o debugsub.o ievent.o keystat.o nevent.o \
	statsave.o timing.o

CODECNVOBJS = \
	codecnv/eucsjis.o codecnv/eucucs2.o codecnv/sjiseuc.o \
	codecnv/sjisucs2.o codecnv/tcswap16.o codecnv/tcswap32.o \
	codecnv/textcnv.o codecnv/ucs2sjis.o codecnv/ucs2utf8.o \
	codecnv/utf8ucs2.o

COMMONOBJS = \
	common/_memory.o common/bmpdata.o common/lstarray.o common/milstr.o \
	common/parts.o common/profile.o common/rect.o common/resize.o \
	common/strres.o common/textfile.o common/wavefile.o

EMBEDOBJS = \
	embed/vramhdl.o embed/vrammix.o \
	embed/menu/dlgabout.o embed/menu/dlgcfg.o embed/menu/filesel.o \
	embed/menu/menustr.o \
	embed/menubase/menubase.o embed/menubase/menudlg.o \
	embed/menubase/menuicon.o embed/menubase/menumbox.o \
	embed/menubase/menures.o embed/menubase/menusys.o \
	embed/menubase/menuvram.o

FDDOBJS = \
	fdd/diskdrv.o fdd/fdd_2d.o fdd/fdd_d88.o fdd/fdd_ini.o \
	fdd/fdd_mtr.o fdd/fddfile.o fdd/newdisk.o

FONTOBJS = \
	font/font.o font/fontdata.o font/fontmake.o font/fontx1.o

IOOBJS = \
	io/cgrom.o io/cmt.o io/crtc.o io/ctc.o io/dipsw.o io/dmac.o \
	io/fdc.o io/iocore.o io/memio.o io/pcg.o io/ppi.o io/sio.o \
	io/sndboard.o io/subcpu.o io/vramio.o

SOUNDOBJS = \
	sound/opm.o sound/opmgenc.o sound/opmgeng.o sound/psg.o \
	sound/psggenc.o sound/psggeng.o sound/sndcsec.o sound/sndctrl.o \
	sound/sound.o sound/x1f.o

# Z80 コアは C 版 (z80c)。z80x/z80a* は x86 asm のため PSP では使えない。
Z80OBJS = \
	z80c/z80c.o z80c/z80c_cb.o z80c/z80c_ix.o z80c/z80c_iy.o \
	z80c/z80c_mn.o z80c/z80c_sb.o z80c/z80dmap.o z80c/z80mem.o

# vram は libretro/Makefile.common と同じ個別列挙 (x86 asm 版のある
# ファイルを除いた C 実装のみ)。
VRAMOBJS = \
	vram/make15.o vram/make24.o vram/makeatr.o vram/makechr.o \
	vram/makemix.o vram/makescrn.o vram/makesub.o vram/maketxth.o \
	vram/maketxtl.o vram/palettes.o vram/sdraw.o vram/sdrawq16.o \
	vram/scrndraw.o vram/vram.o

COREOBJS = \
	$(ROOTOBJS) $(CODECNVOBJS) $(COMMONOBJS) $(EMBEDOBJS) $(FDDOBJS) \
	$(FONTOBJS) $(IOOBJS) $(SOUNDOBJS) $(Z80OBJS) $(VRAMOBJS)

# ------------------------------------------------------- フロントエンド objs
FRONTEND_OBJS = \
	psp/xmil.o psp/scrnmng.o psp/soundmng.o psp/sysmng.o psp/sysmenu.o \
	psp/taskmng.o psp/timemng.o psp/trace.o psp/dosio.o psp/fontmng.o \
	psp/ini.o psp/joymng.o psp/mousemng.o psp/selfexec.o psp/perf.o psp/gu.o psp/softkbd.o psp/pspmenu.o

OBJS = $(COREOBJS) $(FRONTEND_OBJS)

TARGET = xmil

# PRX 形式 (px68k と同様。実行時ロードされるモジュールのリンクのため)
BUILD_PRX = 1

PSPDEV = $(shell psp-config -d)
PSPBIN = $(PSPDEV)/psp/bin
SDL_CONFIG = $(PSPBIN)/sdl2-config

# 最近の pspdev の sdl-config は prefix が壊れている (/psp) ので修正する
# (px68k から流用。フロントエンドが SDL を使う場合に効く。コアには不要)
SDL_INCLUDE =	$(shell $(SDL_CONFIG) --cflags | sed "s|-I/psp/|-I$(PSPDEV)/psp/|g")
SDL_LIB =	$(shell $(SDL_CONFIG) --libs | sed "s|-L/psp/|-L$(PSPDEV)/psp/|g")

# psp/ を先頭に置き compiler.h は必ず psp/compiler.h が使われるようにする。
# libretro/ は末尾: コアが参照するポート層ヘッダ (dosio.h scrnmng.h
# soundmng.h sysmng.h fontmng.h taskmng.h timemng.h trace.h xmil.h など) を
# 当面 libretro 版から借りる。統合時にフロントエンドが psp/ に同名ヘッダを
# 置けばそちらが優先される。
INCDIR = psp . codecnv common embed embed/menu embed/menubase fdd font io \
	sound vram z80c libretro

# -G0: libretro の PSP ターゲットに合わせる。px68k では -G8 (小データを
# gp 相対で参照、約 -14%/frame) を使っているが、割り込みハンドラと $gp の
# 関係を監査してからでないと危険なので、まずは -G0 で始める。
# PGO: make PGO=gen で計測ビルド (PPSSPP で autotest を走らせると gcda が
# ~/.config/ppsspp/<このディレクトリの絶対パス>/ に落ちる)。回収して
# make PGO=use で最適化ビルド。どちらも make clean してから。
ifeq ($(PGO),gen)
PGOFLAGS = -DPXMIL_GCOV -fprofile-generate=ms0:/PSP/GAME/PXMIL/pgo \
	-fprofile-prefix-path=$(PWD) -fprofile-update=single
else ifeq ($(PGO),use)
PGOFLAGS = -fprofile-use=pgo -fprofile-prefix-path=$(PWD) \
	-fprofile-correction -Wno-missing-profile
endif

# バージョン文字列 (メニューに表示)
PXMIL_VER := $(shell date +%Y%m%d)-$(shell git rev-parse --short HEAD 2>/dev/null || echo dev)

CFLAGS = -G8 -O2 -Wall $(PGOFLAGS) $(SDL_INCLUDE) -DPXMIL_VER='"$(PXMIL_VER)"'

CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti
ASFLAGS = $(CFLAGS)

LIBDIR =
LDFLAGS =
# sdl2-config --libs が -lSDL2main -lSDL2 と PSP 側依存 (GU/GE/audio 等) を
# 返す。残りは newlib/libm。
LIBS = $(SDL_LIB) -lm -lpsppower -lpspsystemctrl_user

EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = X millennium for PSP
PSP_EBOOT_ICON = assets/icon0.png

PSPSDK = $(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build.mak

# コアのみコンパイル (リンクしない)。フロントエンド開発と並行用。
objs: $(COREOBJS)

.PHONY: objs

# バージョンが変わったらメニューを作り直す (build.mak の include 後に
# 置くこと: 先頭に置くとデフォルトターゲットになってしまう)
psp/pspmenu.o: $(wildcard .git/HEAD .git/index)
